### ISSUE TITLE
When I use php7,I got "JSON DECODE ERROR"

### ISSUE THREAD

**Issue by lidongran128** [regendsoh/xmrig-proxy-dashboard#1]
The VPS's System is CentOS7,and php version is 7.  When I use php7,I got "JSON DECODE ERROR".
I try uninstall php7 and install php 5.6.It work!!

I want to tell everyone ，Pay attention to this issue。

sorry my English 😄.
Thanks regendsoh's nice job!

**Comment by regendsoh** [comment]
I will close this issue, should you have further issues with the project, please create a new thread.
